package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Gold_GitGithubComK88936goldGitRefsHeadsMain'
in the project with id = 'Gold', and delete the patch script.
*/
create(RelativeId("Gold"), GitVcsRoot({
    id("Gold_GitGithubComK88936goldGitRefsHeadsMain")
    name = "git@github.com:k88936/gold.git#refs/heads/main"
    url = "git@github.com:k88936/gold.git"
    branch = "refs/heads/main"
    branchSpec = "refs/heads/*"
    authMethod = uploadedKey {
        uploadedKey = "k99836 github"
    }
}))

