package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'SourceOf_MyCollection_GitGithubComK88936myCollectionGitRefsHeadsMain'
in the project with id = 'SourceOf_MyCollection', and delete the patch script.
*/
create(RelativeId("SourceOf_MyCollection"), GitVcsRoot({
    id("SourceOf_MyCollection_GitGithubComK88936myCollectionGitRefsHeadsMain")
    name = "git@github.com:k88936/my-collection.git#refs/heads/main"
    url = "git@github.com:k88936/my-collection.git"
    branch = "refs/heads/main"
    branchSpec = "refs/heads/*"
    authMethod = uploadedKey {
        uploadedKey = "k99836 github"
    }
}))

