package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.DockerRegistryConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.GitHubAppConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.S3CompatibleStorage
import jetbrains.buildServer.configs.kotlin.projectFeatures.dockerRegistry
import jetbrains.buildServer.configs.kotlin.projectFeatures.githubAppConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.s3CompatibleStorage
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        expect {
            password("KVTO_RUSTFS_ACCESS_KEY", "credentialsJSON:5fc336a3-cb50-4cf1-aabd-7b2e77165b02")
        }
        update {
            password("KVTO_RUSTFS_ACCESS_KEY", "credentialsJSON:dbd9d18e-531c-4b59-8f18-85ee3dbf0757")
        }
        expect {
            password("KVTO_RUSTFS_SECRET_KEY", "credentialsJSON:2363a321-c78d-4a04-ad69-40c1fec750d5")
        }
        update {
            password("KVTO_RUSTFS_SECRET_KEY", "credentialsJSON:fe76ba66-ec2d-443d-bda6-ade2fa15191f")
        }
    }

    features {
        val feature1 = find<DockerRegistryConnection> {
            dockerRegistry {
                id = "DOCKER_REGISTRY_CONNECTION"
                name = "Docker Registry"
                userName = "kvtodev"
                password = "credentialsJSON:a43b4956-2b9e-457c-bf3c-6e04db2adc38"
            }
        }
        feature1.apply {
        }
        val feature2 = find<S3CompatibleStorage> {
            s3CompatibleStorage {
                id = "PROJECT_EXT_3"
                accessKeyID = "PrunStQTawifpVN8A1Mc"
                accessKey = "credentialsJSON:535a3e4e-5376-4808-8374-fc82c559bea5"
                endpoint = "https://rustfs.k88936.top"
                bucketName = "teamcity-artifact"
                param("aws.region.name", "")
                param("aws.use.default.credential.provider.chain", "")
                param("storage.s3.forceVirtualHostAddressing", "")
            }
        }
        feature2.apply {
            accessKeyID = "SHd9FvJ8Gcr1s3eh6bCU"
            accessKey = "credentialsJSON:fe76ba66-ec2d-443d-bda6-ade2fa15191f"
        }
        val feature3 = find<GitHubAppConnection> {
            githubAppConnection {
                id = "PROJECT_EXT_4"
                displayName = "k88936/TeamCity"
                appId = "2210972"
                clientId = "Iv23li1V4XlIXvtqlwq1"
                clientSecret = "credentialsJSON:b39a599e-3ddc-4b9c-b560-34f11c98a5f9"
                privateKey = "credentialsJSON:db545cdc-cf1c-4643-8881-46d084fdd7ab"
                webhookSecret = "credentialsJSON:0f3bb38b-c2c6-4fec-a8ca-6287f91611a8"
                ownerUrl = "https://github.com/k88936"
                useUniqueCallback = true
            }
        }
        feature3.apply {
        }
    }
}
