package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.dockerRegistry
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'Fcalender'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("Fcalender")) {
    features {
        add {
            dockerRegistry {
                id = "PROJECT_EXT_4"
                name = "Docker Registry"
                url = "https://ghcr.io"
                userName = "k88936"
                password = "credentialsJSON:87641c9a-897e-4143-b113-ffdc84599188"
            }
        }
    }
}
