package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.githubAppConnection
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'FcalenderFrontend'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("FcalenderFrontend")) {
    features {
        add {
            githubAppConnection {
                id = "PROJECT_EXT_3"
                displayName = "kvtoTeamCity"
                appId = "2210964"
                clientId = "Iv23liEwFHHOm1dP9jz4"
                clientSecret = "credentialsJSON:55874d83-8a06-414f-a42e-7f70ba6e8ce0"
                privateKey = "credentialsJSON:ad71d882-2c96-411c-b1f1-24913556e532"
                webhookSecret = "credentialsJSON:76079ca7-51d8-40f4-9c5c-f1c4b1261adc"
                ownerUrl = "https://github.com/k88936"
                useUniqueCallback = true
            }
        }
    }
}
