package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'UnityProjects_2dPixelGame'
in the project with id = 'UnityProjects', and delete the patch script.
*/
create(RelativeId("UnityProjects"), Project({
    id("UnityProjects_2dPixelGame")
    name = "2D Pixel Game"
}))

