package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'WebstormProjects_ReactNativeDemo'
in the project with id = 'WebstormProjects', and delete the patch script.
*/
create(RelativeId("WebstormProjects"), Project({
    id("WebstormProjects_ReactNativeDemo")
    name = "React Native Demo"
}))

