package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Gold_Build'
in the project with id = 'Gold', and delete the patch script.
*/
create(RelativeId("Gold"), BuildType({
    id("Gold_Build")
    name = "Build"

    vcs {
        root(RelativeId("Gold_GitGithubComK88936goldGitRefsHeadsMain"))
    }

    steps {
        step {
            id = "cargo"
            type = "cargo"
            param("cargo-command", "build")
        }
    }

    triggers {
        vcs {
        }
    }

    features {
        perfmon {
        }
    }
}))

