package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.buildSteps.nodeJS
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'SourceOf_Build'
in the project with id = 'SourceOf', and delete the patch script.
*/
create(RelativeId("SourceOf"), BuildType({
    id("SourceOf_Build")
    name = "Build"

    params {
        password("env.SECRET_KEY", "credentialsJSON:6d9f4af1-89b3-41a3-9bcc-fde1bdd8e7f9")
        param("env.BUCKET_NAME", "software-release")
        param("env.AWS_REGION", "us-east-1")
        password("env.ACCESS_KEY", "credentialsJSON:e2bf46ef-fcae-472d-a934-117a88db5241")
    }

    vcs {
        root(RelativeId("SourceOf_GitGithubComK88936sourceOfGitRefsHeadsMain"))
    }

    steps {
        nodeJS {
            id = "nodejs_runner"
            shellScript = """
                npm ci
                npm run test
                npm build
            """.trimIndent()
        }
    }

    triggers {
        vcs {
        }
    }

    features {
        perfmon {
        }
    }
}))

