package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.triggers.finishBuildTrigger
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'SourceOf_Deploy'
in the project with id = 'SourceOf_MyCollection', and delete the patch script.
*/
create(RelativeId("SourceOf_MyCollection"), BuildType({
    id("SourceOf_Deploy")
    name = "Deploy"

    enablePersonalBuilds = false
    type = BuildTypeSettings.Type.DEPLOYMENT
    maxRunningBuilds = 1

    triggers {
        finishBuildTrigger {
            buildType = "SourceOf_Build"
        }
    }

    dependencies {
        artifacts(RelativeId("SourceOf_Build")) {
            buildRule = lastSuccessful()
            artifactRules = "/"
        }
    }
}))

