package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'SourceOf_MyCollection_Build'
in the project with id = 'SourceOf_MyCollection', and delete the patch script.
*/
create(RelativeId("SourceOf_MyCollection"), BuildType({
    id("SourceOf_MyCollection_Build")
    name = "Build"

    vcs {
        root(RelativeId("SourceOf_MyCollection_GitGithubComK88936myCollectionGitRefsHeadsMain"))
    }

    triggers {
        vcs {
        }
    }

    features {
        perfmon {
        }
    }
}))

