package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'SourceOf_MyCollection'
in the project with id = 'SourceOf', and delete the patch script.
*/
create(RelativeId("SourceOf"), Project({
    id("SourceOf_MyCollection")
    name = "DeployPage"
}))

