package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Blogs_GitGithubComK88936blogsGitRefsHeadsMain'
in the project with id = 'Blogs', and delete the patch script.
*/
create(RelativeId("Blogs"), GitVcsRoot({
    id("Blogs_GitGithubComK88936blogsGitRefsHeadsMain")
    name = "git@github.com:k88936/blogs.git#refs/heads/main"
    url = "git@github.com:k88936/blogs.git"
    branch = "refs/heads/main"
    branchSpec = "refs/heads/*"
    authMethod = uploadedKey {
        uploadedKey = "id_rsa"
    }
}))

