package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'GitGithubComK88936k88936githubIoGit_GitGithubComK88936k88936githubIoGit'
in the project with id = 'GitGithubComK88936k88936githubIoGit', and delete the patch script.
*/
create(RelativeId("GitGithubComK88936k88936githubIoGit"), GitVcsRoot({
    id("GitGithubComK88936k88936githubIoGit_GitGithubComK88936k88936githubIoGit")
    name = "git@github.com:k88936/k88936.github.io.git"
    url = "git@github.com:k88936/k88936.github.io.git"
    branch = "refs/heads/main"
    authMethod = uploadedKey {
        userName = "git"
        uploadedKey = "id_rsa"
    }
}))

