package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Nextcloud_GitGithubComK88936nextcloudGitRefsHeadsMaster'
in the project with id = 'Nextcloud', and delete the patch script.
*/
create(RelativeId("Nextcloud"), GitVcsRoot({
    id("Nextcloud_GitGithubComK88936nextcloudGitRefsHeadsMaster")
    name = "git@github.com:k88936/nextcloud.git#refs/heads/master"
    url = "git@github.com:k88936/nextcloud.git"
    branch = "refs/heads/master"
    branchSpec = "refs/heads/*"
    authMethod = uploadedKey {
        uploadedKey = "id_rsa"
    }
}))

