package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'Nextcloud_GitGithubComK88936nextcloudGitRefsHeadsMaster'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("Nextcloud_GitGithubComK88936nextcloudGitRefsHeadsMaster")) {
    val expected = GitVcsRoot({
        id("Nextcloud_GitGithubComK88936nextcloudGitRefsHeadsMaster")
        name = "git@github.com:k88936/nextcloud.git#refs/heads/master"
        url = "git@github.com:k88936/nextcloud.git"
        branch = "refs/heads/master"
        branchSpec = "refs/heads/*"
        authMethod = uploadedKey {
            uploadedKey = "id_rsa"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        name = "git@github.com:k88936/nextcloud.git#refs/heads/main"
        branch = "refs/heads/main"
    }

}
