package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'OllamaProxy_GitGithubComK88936ollamaProxyGitRefsHeadsMain'
in the project with id = 'OllamaProxy', and delete the patch script.
*/
create(RelativeId("OllamaProxy"), GitVcsRoot({
    id("OllamaProxy_GitGithubComK88936ollamaProxyGitRefsHeadsMain")
    name = "git@github.com:k88936/ollama-proxy.git#refs/heads/main"
    url = "git@github.com:k88936/ollama-proxy.git"
    branch = "refs/heads/main"
    branchSpec = "refs/heads/*"
    authMethod = uploadedKey {
        uploadedKey = "id_rsa"
    }
}))

