package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Rustdesk_GitGithubComK88936rustdeskGitRefsHeadsMaster'
in the project with id = 'Rustdesk', and delete the patch script.
*/
create(RelativeId("Rustdesk"), GitVcsRoot({
    id("Rustdesk_GitGithubComK88936rustdeskGitRefsHeadsMaster")
    name = "git@github.com:k88936/rustdesk.git#refs/heads/master"
    url = "git@github.com:k88936/rustdesk.git"
    branch = "refs/heads/master"
    branchSpec = "refs/heads/*"
    authMethod = uploadedKey {
        uploadedKey = "id_rsa"
    }
}))

