package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'TeamcityAgent_GitGithubComK88936teamcityAgentGitRefsHeadsMain'
in the project with id = 'TeamcityAgent', and delete the patch script.
*/
create(RelativeId("TeamcityAgent"), GitVcsRoot({
    id("TeamcityAgent_GitGithubComK88936teamcityAgentGitRefsHeadsMain")
    name = "git@github.com:k88936/teamcity-agent.git#refs/heads/main"
    url = "git@github.com:k88936/teamcity-agent.git"
    branch = "refs/heads/main"
    branchSpec = "refs/heads/*"
    authMethod = uploadedKey {
        uploadedKey = "id_rsa"
    }
}))

