package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'UnityProjects_2dPixelGame_GitGithubCom20220120802dPixelGameGitRefsHeadsMain'
in the project with id = 'UnityProjects_2dPixelGame', and delete the patch script.
*/
create(RelativeId("UnityProjects_2dPixelGame"), GitVcsRoot({
    id("UnityProjects_2dPixelGame_GitGithubCom20220120802dPixelGameGitRefsHeadsMain")
    name = "git@github.com:2022012080/2D-Pixel-Game.git#refs/heads/main"
    url = "git@github.com:2022012080/2D-Pixel-Game.git"
    branch = "refs/heads/main"
    branchSpec = "refs/heads/*"
    authMethod = uploadedKey {
        uploadedKey = "id_rsa"
    }
}))

