package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'WebstormProjects_ReactNativeDemo_GitGithubComK88936reactNativeDemoGitRefsHeadsMain'
in the project with id = 'WebstormProjects_ReactNativeDemo', and delete the patch script.
*/
create(RelativeId("WebstormProjects_ReactNativeDemo"), GitVcsRoot({
    id("WebstormProjects_ReactNativeDemo_GitGithubComK88936reactNativeDemoGitRefsHeadsMain")
    name = "git@github.com:k88936/react-native-demo.git#refs/heads/main"
    url = "git@github.com:k88936/react-native-demo.git"
    branch = "refs/heads/main"
    branchSpec = "refs/heads/*"
    authMethod = uploadedKey {
        uploadedKey = "id_rsa"
    }
}))

