package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.sshAgent
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'FcalenderBackendBuild'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("FcalenderBackendBuild")) {
    features {
        add {
            sshAgent {
                teamcitySshKey = "id_rsa"
            }
        }
    }
}
