package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'FcalenderFrontendBuild'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("FcalenderFrontendBuild")) {
    params {
        expect {
            param("env.ANDROID_KEY_ALIAS", "release")
        }
        update {
            password("env.ANDROID_KEY_ALIAS", "credentialsJSON:35065075-71ae-4db5-9966-cfe20a462105")
        }
        expect {
            param("env.ANDROID_KEY_PASSWORD", "fcalendar")
        }
        update {
            password("env.ANDROID_KEY_PASSWORD", "credentialsJSON:4fb0aac1-ef07-4299-9d16-76bc76f4879f")
        }
    }
}
