package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.notifications
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'FcalenderFrontendBuild'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("FcalenderFrontendBuild")) {
    features {
        add {
            notifications {
                notifierSettings = emailNotifier {
                    email = "k88936@qq.com"
                }
                buildFailed = true
            }
        }
    }
}
