package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.triggers.VcsTrigger
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'FcalenderFrontendBuild'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("FcalenderFrontendBuild")) {
    triggers {
        val trigger1 = find<VcsTrigger> {
            vcs {
                branchFilter = "                +:frontend*"
            }
        }
        trigger1.apply {
            branchFilter = "+:frontend*"

        }
    }
}
