package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.DockerCommandStep
import jetbrains.buildServer.configs.kotlin.buildSteps.dockerCommand
import jetbrains.buildServer.configs.kotlin.buildSteps.sshExec
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'FcalenderBackendBuild'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("FcalenderBackendBuild")) {
    expectSteps {
        dockerCommand {
            id = "build"
            commandType = build {
                source = file {
                    path = "backend/Dockerfile"
                }
                namesAndTags = "kvtodev/fcalendar:%teamcity.build.branch%"
                commandArgs = "--progress=plain"
            }
        }
        dockerCommand {
            id = "push"
            commandType = push {
                namesAndTags = "kvtodev/fcalendar:%teamcity.build.branch%"
                removeImageAfterPush = false
            }
        }
        sshExec {
            id = "deploy_dev"
            commands = """
                cd dev
                sudo docker-compose pull
                sudo docker-compose down
                sudo docker-compose up -d
            """.trimIndent()
            targetUrl = "fcalendar.k88936.top"
            authMethod = sshAgent {
                username = "ubuntu"
            }
        }
    }
    steps {
        update<DockerCommandStep>(0) {
            clearConditions()
            commandType = build {
                source = file {
                    path = "backend/Dockerfile"
                }
                contextDir = ""
                platform = DockerCommandStep.ImagePlatform.Any
                namesAndTags = "kvtodev/fcalendar:%teamcity.build.branch%"
                commandArgs = "--progress=plain --no-cache"
            }
        }
    }
}
