package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Fernflower_Deploy'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Fernflower_Deploy")) {
    params {
        add {
            password("env.GITHUB_TOKEN", "credentialsJSON:04d96fb0-dbf8-457b-be29-2327ab11dd68")
        }
    }
}
