package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.NodeJSBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.nodeJS
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'gitgithubcomk88936k88936githubiogit_Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("gitgithubcomk88936k88936githubiogit_Build")) {
    expectSteps {
        nodeJS {
            id = "nodejs_runner"
            shellScript = """
                npm install
                npm run build
            """.trimIndent()
        }
        script {
            name = "Git Push Changes"
            id = "git_push"
            scriptContent = """
                git config user.email "teamcity@kvto.dev"
                git config user.name "teamcity"
                git add -A
                git commit -m"build pages"
                git push --force
            """.trimIndent()
        }
    }
    steps {
        update<NodeJSBuildStep>(0) {
            enabled = false
            clearConditions()
        }
        update<ScriptBuildStep>(1) {
            enabled = false
            clearConditions()
        }
        insert(2) {
            script {
                id = "simpleRunner"
                scriptContent = """
                    git config --get core.sshCommand
                    echo ${'$'}GIT_SSH_COMMAND
                    
                    unset GIT_SSH_COMMAND
                    git config --unset core.sshCommand
                    
                    git pull
                """.trimIndent()
            }
        }
    }
}
