package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'GitGithubComK88936k88936githubIoGit_Build'
in the project with id = 'GitGithubComK88936k88936githubIoGit', and delete the patch script.
*/
create(RelativeId("GitGithubComK88936k88936githubIoGit"), BuildType({
    id("GitGithubComK88936k88936githubIoGit_Build")
    name = "Build"
}))

