package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildStep
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Gold_Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Gold_Build")) {
    check(name == "Build") {
        "Unexpected name: '$name'"
    }
    name = "Build_win"

    check(artifactRules == "") {
        "Unexpected option value: artifactRules = $artifactRules"
    }
    artifactRules = """target\release\gold.exe"""

    expectSteps {
        step {
            id = "cargo"
            type = "cargo"
            param("cargo-command", "build")
        }
    }
    steps {
        update<BuildStep>(0) {
            clearConditions()
            param("cargo-build-release", "true")
        }
    }

    requirements {
        add {
            exists("env.WIN_PLATFORM")
        }
    }
}
