package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Gold_Deploy'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Gold_Deploy")) {
    params {
        expect {
            password("env.S3_ACCESS_KEY", "credentialsJSON:23688bbb-1b91-46ba-b441-09702c979512")
        }
        update {
            password("env.S3_ACCESS_KEY", "credentialsJSON:b15e9090-d3a1-49c5-9122-2af653fcd372")
        }
        expect {
            password("env.S3_SECRET_KEY", "credentialsJSON:486eb30c-545f-49f3-b1b8-e4a07c95456a")
        }
        update {
            password("env.S3_SECRET_KEY", "credentialsJSON:12b9893f-0fa3-4daf-9b11-63751aaa96a0")
        }
    }

    requirements {
        remove {
            exists("env.PLATFORM_LINUX")
        }
        add {
            exists("env.PLATFORM_LINUX", "RQ_1")
        }
    }

    expectDisabledSettings()
    updateDisabledSettings("RQ_1")
}
