package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.CargoBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.cargo
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Gold_BuildLinux'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Gold_BuildLinux")) {
    expectSteps {
        cargo {
            id = "cargo"
            command = build {
                release = true
            }
        }
    }
    steps {
        update<CargoBuildStep>(0) {
            enabled = false
            clearConditions()
        }
        insert(1) {
            script {
                id = "simpleRunner"
                scriptContent = "cargo build --release"
                dockerImage = "kvtodev/ci-containers:rust"
            }
        }
    }
}
