package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Gold_Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Gold_Build")) {
    expectSteps {
        step {
            id = "cargo"
            type = "cargo"
            param("cargo-command", "build")
        }
    }
    steps {
        insert(0) {
            script {
                id = "simpleRunner"
                scriptContent = "cargo build --release"
            }
        }
    }

    requirements {
        add {
            exists("env.WIN_PLATFORM")
        }
    }
}
