package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.GradleBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Keetcoder_Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Keetcoder_Build")) {
    expectSteps {
        gradle {
            id = "gradle_runner"
            tasks = "buildPlugin"
        }
    }
    steps {
        update<GradleBuildStep>(0) {
            clearConditions()
            jdkHome = "%env.JDK_21_0_x64%"
            param("teamcity.kubernetes.executor.pull.policy", "")
        }
    }
}
