package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the buildType with id = 'LocalRouter_Scoop'
from your code, and delete the patch script.
*/
deleteBuildType(RelativeId("LocalRouter_Scoop"))

