package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.buildSteps.dockerCommand
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Nextcloud_Build'
in the project with id = 'Nextcloud', and delete the patch script.
*/
create(RelativeId("Nextcloud"), BuildType({
    id("Nextcloud_Build")
    name = "Build"

    vcs {
        root(RelativeId("Nextcloud_GitGithubComK88936nextcloudGitRefsHeadsMaster"))
    }

    steps {
        script {
            id = "simpleRunner"
            scriptContent = "./generate-stackbrew-library.sh"
        }
        script {
            id = "simpleRunner_1"
            scriptContent = "./update.sh"
        }
        dockerCommand {
            id = "DockerCommand"
            commandType = build {
                source = file {
                    path = "31/apache/Dockerfile"
                }
                namesAndTags = "kvtodev:nextcloud"
            }
        }
        dockerCommand {
            id = "DockerCommand_1"
            commandType = push {
                namesAndTags = "kvtodev:nextcloud"
            }
        }
    }

    triggers {
        vcs {
        }
    }

    features {
        perfmon {
        }
    }
}))

