package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.dockerCommand
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Nextcloud_Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Nextcloud_Build")) {
    expectSteps {
        script {
            id = "simpleRunner"
            scriptContent = "./generate-stackbrew-library.sh"
        }
        script {
            id = "simpleRunner_1"
            scriptContent = "./update.sh"
        }
        dockerCommand {
            id = "DockerCommand"
            commandType = build {
                source = file {
                    path = "31/apache/Dockerfile"
                }
                namesAndTags = "kvtodev/nextcloud:latest"
            }
        }
        dockerCommand {
            id = "DockerCommand_1"
            commandType = push {
                namesAndTags = "kvtodev/nextcloud:latest"
                removeImageAfterPush = false
            }
        }
    }
    steps {
        items.removeAt(0)
    }
}
