package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.triggers.finishBuildTrigger
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'OllamaProxy_Deploy'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("OllamaProxy_Deploy")) {
    triggers {
        add {
            finishBuildTrigger {
                buildType = "OllamaProxy_BuildLinux"
                successfulOnly = true
            }
        }
        add {
            finishBuildTrigger {
                buildType = "OllamaProxy_BuildWin"
                successfulOnly = true
            }
        }
    }
}
