package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'OllamaProxy_BuildLinux'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("OllamaProxy_BuildLinux")) {
    check(artifactRules == "") {
        "Unexpected option value: artifactRules = $artifactRules"
    }
    artifactRules = "target/release/ollama-proxy"
}
