package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'OllamaProxy_BuildWin'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("OllamaProxy_BuildWin")) {
    check(artifactRules == "") {
        "Unexpected option value: artifactRules = $artifactRules"
    }
    artifactRules = """target\release\ollama-proxy.exe"""
}
