package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ReactNativeDemo_Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ReactNativeDemo_Build")) {
    params {
        expect {
            password("env.CONTINUE_API_KEY", "")
        }
        update {
            password("env.CONTINUE_API_KEY", "credentialsJSON:0af0457d-0ac1-4e56-83e7-6e93306effa7")
        }
    }
}
