package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ReactNativeDemo_Deploy'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ReactNativeDemo_Deploy")) {
    params {
        expect {
            password("env.FEISHU_ACCESS_TOKEN", "")
        }
        update {
            password("env.FEISHU_ACCESS_TOKEN", "credentialsJSON:81365cbb-42af-4197-a1bc-10e8a14b6fa0")
        }
    }
}
