package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Rustdesk_BuildFlutter'
in the project with id = 'Rustdesk', and delete the patch script.
*/
create(RelativeId("Rustdesk"), BuildType({
    id("Rustdesk_BuildFlutter")
    name = "Build_flutter"
}))

