package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.buildSteps.cargo
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Rustdesk_Build'
in the project with id = 'Rustdesk', and delete the patch script.
*/
create(RelativeId("Rustdesk"), BuildType({
    id("Rustdesk_Build")
    name = "Build"

    vcs {
        root(RelativeId("Rustdesk_GitGithubComK88936rustdeskGitRefsHeadsMaster"))
    }

    steps {
        cargo {
            id = "cargo"
            command = build {
                release = true
            }
        }
    }

    triggers {
        vcs {
        }
    }

    features {
        perfmon {
        }
    }
}))

