package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Shotmd_Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Shotmd_Build")) {
    params {
        remove {
            text("env.QT_INSTALL", """C:\Qt\6.9.1\msvc2022_64""")
        }
        add {
            text("QT_INSTALL", """C:\Qt\6.9.1\msvc2022_64""")
        }
    }
}
