package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.triggers.schedule
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'SourceOf_Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("SourceOf_Build")) {
    triggers {
        add {
            schedule {
                triggerBuild = always()
                withPendingChangesOnly = false
            }
        }
    }
}
