package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'TDPixelGame_Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("TDPixelGame_Build")) {
    check(artifactRules == """
        Build\Windows\*
        -:Build\Windows\DemoGame_BackUpThisFolder_ButDontShipItWithYourGame
        -:Build\Windows\world simulator_BurstDebugInformation_DoNotShip
    """.trimIndent()) {
        "Unexpected option value: artifactRules = $artifactRules"
    }
    artifactRules = """
        Build\Windows\=>/
        -:Build\Windows\DemoGame_BackUpThisFolder_ButDontShipItWithYourGame
        -:Build\Windows\world simulator_BurstDebugInformation_DoNotShip
    """.trimIndent()
}
