package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.buildSteps.dockerCommand
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'TeamcityAgent_Build'
in the project with id = 'TeamcityAgent', and delete the patch script.
*/
create(RelativeId("TeamcityAgent"), BuildType({
    id("TeamcityAgent_Build")
    name = "Build"

    vcs {
        root(RelativeId("TeamcityAgent_GitGithubComK88936teamcityAgentGitRefsHeadsMain"))
    }

    steps {
        dockerCommand {
            id = "DockerCommand"
            commandType = build {
                source = file {
                    path = "Dockerfile"
                }
                namesAndTags = "kvtodev/teamcity-agent"
            }
        }
    }

    triggers {
        vcs {
        }
    }

    features {
        perfmon {
        }
    }
}))

