package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.dockerRegistryConnections
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'TeamcityAgent_Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("TeamcityAgent_Build")) {
    features {
        add {
            dockerRegistryConnections {
                loginToRegistry = on {
                    dockerRegistryId = "PROJECT_EXT_4"
                }
            }
        }
    }
}
