package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.CargoBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.cargo
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'TunetRust_Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("TunetRust_Build")) {
    expectSteps {
        cargo {
            id = "cargo"
            command = build {
                buildPackage = "tunet tunet-service"
                release = true
            }
        }
    }
    steps {
        update<CargoBuildStep>(0) {
            clearConditions()
            command = build {
                buildPackage = "tunet,tunet-service"
                type = CargoBuildStep.BuildType.Auto
                typeName = ""
                release = true
                features = ""
                defaultFeatures = true
                target = "tunet tunet-service"
                manifest = ""
                parallelJobsNumber = ""
            }
        }
    }
}
