package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'UnityProjects_2dPixelGame_Build'
in the project with id = 'UnityProjects_2dPixelGame', and delete the patch script.
*/
create(RelativeId("UnityProjects_2dPixelGame"), BuildType({
    id("UnityProjects_2dPixelGame_Build")
    name = "Build"

    vcs {
        root(RelativeId("UnityProjects_2dPixelGame_GitGithubCom20220120802dPixelGameGitRefsHeadsMain"))
    }

    steps {
        step {
            id = "unity"
            type = "unity"
            param("unityVersion", "6000.0.49")
            param("projectPath", "")
        }
    }

    triggers {
        vcs {
        }
    }

    features {
        perfmon {
        }
    }
}))

