package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'WebstormProjects_ReactNativeDemo_Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("WebstormProjects_ReactNativeDemo_Build")) {
    expectSteps {
        script {
            id = "nodejs_runner"
            scriptContent = """
                source /etc/profile
                npm install
                npx expo prebuild
                cd android
                ./gradlew assembleRelease --no-daemon --parallel
            """.trimIndent()
            dockerImage = "kvtodev/ci-containers:react-native"
            dockerPull = true
            dockerRunParameters = "--rm -v /root/.m2:/root/.m2 -v /root/.gradle:/root/.gradle/"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            clearConditions()
            scriptContent = """
                source /etc/profile
                npm install
                npx expo prebuild
                cd android
                export GRADLE_OPTS="${'$'}GRADLE_OPTS -Dhttps.protocols=TLSv1.2,TLSv1.3"
                ./gradlew assembleRelease --no-daemon --parallel
            """.trimIndent()
            param("teamcity.kubernetes.executor.pull.policy", "")
        }
    }
}
