package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'WebstormProjects_ReactNativeDemo_Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("WebstormProjects_ReactNativeDemo_Build")) {
    check(artifactRules == "") {
        "Unexpected option value: artifactRules = $artifactRules"
    }
    artifactRules = "android/app/build/outputs/apk/release/app-release.apk"
}
