package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'WebstormProjects_ReactNativeDemo_Release'
in the project with id = 'WebstormProjects_ReactNativeDemo', and delete the patch script.
*/
create(RelativeId("WebstormProjects_ReactNativeDemo"), BuildType({
    id("WebstormProjects_ReactNativeDemo_Release")
    name = "Release"

    enablePersonalBuilds = false
    type = BuildTypeSettings.Type.DEPLOYMENT
    maxRunningBuilds = 1

    dependencies {
        artifacts(RelativeId("WebstormProjects_ReactNativeDemo_Build")) {
            buildRule = lastSuccessful()
            artifactRules = "*"
        }
    }
}))

