package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'WebstormProjects_ReactNativeDemo_Build'
in the project with id = 'WebstormProjects_ReactNativeDemo', and delete the patch script.
*/
create(RelativeId("WebstormProjects_ReactNativeDemo"), BuildType({
    id("WebstormProjects_ReactNativeDemo_Build")
    name = "Build"

    vcs {
        root(RelativeId("WebstormProjects_ReactNativeDemo_GitGithubComK88936reactNativeDemoGitRefsHeadsMain"))
    }

    steps {
        script {
            id = "simpleRunner"
            scriptContent = """
                npm ci
                npx expo prebuild
                npx react-native build-android --tasks assembleRelease
            """.trimIndent()
            dockerImage = "kvtodev/ci-containers:react-native"
            dockerRunParameters = "--rm"
        }
    }

    triggers {
        vcs {
        }
    }

    features {
        perfmon {
        }
    }
}))

